// ADD YOUR OWN KEYS AND RENAME THIS FILE TO keys.js
const TWITTER_TOKENS = {
  TWITTER_CONSUMER_KEY_ORIG: "SOME KEY",
  TWITTER_CONSUMER_SECRET_ORIG: "SOME SECRET",
  TWITTER_ACCESS_TOKEN_ORIG: "SOME ACCESS TOKEN",
  TWITTER_TOKEN_SECRET_ORIG: "SOME TOKEN SECRET",
  TWITTER_CONSUMER_KEY_DEST: "SOME KEY",
  TWITTER_CONSUMER_SECRET_DEST: "SOME SECRET",
  TWITTER_ACCESS_TOKEN_DEST: "SOME ACCESS TOKEN",
  TWITTER_TOKEN_SECRET_DEST: "SOME TOKEN SECRET"
};

const CONFIG = {
  CONFIG_ORIG: {
    'consumerKey': TWITTER_TOKENS.TWITTER_CONSUMER_KEY_ORIG,
    'consumerSecret': TWITTER_TOKENS.TWITTER_CONSUMER_SECRET_ORIG,
    'accessToken': TWITTER_TOKENS.TWITTER_ACCESS_TOKEN_ORIG,
    'accessTokenSecret': TWITTER_TOKENS.TWITTER_TOKEN_SECRET_ORIG
  },
  CONFIG_DEST: {
    'consumerKey': TWITTER_TOKENS.TWITTER_CONSUMER_KEY_DEST,
    'consumerSecret': TWITTER_TOKENS.TWITTER_CONSUMER_SECRET_DEST,
    'accessToken': TWITTER_TOKENS.TWITTER_ACCESS_TOKEN_DEST,
    'accessTokenSecret': TWITTER_TOKENS.TWITTER_TOKEN_SECRET_DEST
  }
};

const DB_USER = "SOME USER";
const DB_PASSWORD = "SOME PASSWPORD";
const MONGODB = {
  MONGODB_URI: `mongodb://${DB_USER}:${DB_PASSWORD}@ds<SOME_DOMAIN>.mlab.com:<PORT>/<PROJECT_NAME>`
};

const SESSION = {
  COOKIE_KEY: "thisappisawesome"
};

const KEYS = {
  ...TWITTER_TOKENS,
  ...MONGODB,
  ...SESSION
};

module.exports = KEYS;
